# Generated by Django 2.0.2 on 2019-06-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=20)),
            ],
        ),
    ]
